channels:
- omnia
dependencies:
- anaconda-client=1.4.0=py35_0
- clyent=1.2.2=py35_0
- doxygen=1.8.10=0
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyyaml=3.11=py35_4
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=23.0.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.7
  - babel==2.3.3
  - breathe==4.2.0
  - docutils==0.12
  - imagesize==0.7.0
  - jinja2==2.8
  - markupsafe==0.23
  - pygments==2.1.3
  - snowballstemmer==1.2.1
  - sphinx==1.4.1
  - sphinx-rtd-theme==0.1.9
