name: molpher-lib-docs
channels:
- rdkit
- defaults
dependencies:
- bzip2=1.0.6=3
- mkl=11.3.3=0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- psutil=4.3.0=py35_0
- python=3.5.1=0
- boost=1.56.0=py35_3
- rdkit=2016.03.2=np111py35_1
- readline=6.2=2
- setuptools=23.0.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.7
  - babel==2.3.3
  - breathe==4.2.0
  - docutils==0.12
  - imagesize==0.7.0
  - jinja2==2.8
  - markupsafe==0.23
  - pygments==2.1.3
  - pytz==2016.3
  - six==1.10.0
  - snowballstemmer==1.2.1
  - sphinx==1.4.1
  - sphinx-rtd-theme==0.1.9
